#!/bin/bash

#SBATCH --job-name=d2q9-bgk
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=1
#SBATCH --time=01:10:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COMS031424
#SBATCH --output=d2q9-bgk.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
#./d2q9-bgk input_128x128.params obstacles_128x128.dat

#./d2q9-bgk input_128x256.params obstacles_128x256.dat
#./d2q9-bgk input_256x256.params obstacles_256x256.dat
#!/bin/bash

#!/bin/bash

# Outer loop for OMP_NUM_THREADS from 1 to 28
for i in {1..28}
do
  # Inner loop to repeat the command 3 times for each value of i
  for j in {1..3}
  do
    echo "Running iteration $j for OMP_NUM_THREADS=$i"
    env OMP_NUM_THREADS=$i ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
  done
done


